// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, user_id, body, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, user_id, body, created_at
`

type CreateMessageParams struct {
	RoomID    int64              `json:"room_id"`
	UserID    int64              `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// created_at is passed in (not left to DEFAULT now()) so the stored time is when
// the user actually sent the message, not when the persister happened to insert it.
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.RoomID,
		arg.UserID,
		arg.Body,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT recent.room_id, recent.user_id, recent.username, recent.body, recent.created_at
FROM (
    SELECT m.id, m.room_id, m.user_id, u.username, m.body, m.created_at
    FROM messages m
    JOIN users u ON u.id = m.user_id
    WHERE m.room_id = $1
    ORDER BY m.id DESC
    LIMIT 50
) AS recent
ORDER BY recent.id
`

type ListRecentMessagesRow struct {
	RoomID    int64              `json:"room_id"`
	UserID    int64              `json:"user_id"`
	Username  string             `json:"username"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// The last 50 messages of a room, oldest-first (chat reading order).
// The inner query walks idx_messages_room_id_id backwards to grab the NEWEST 50
// without scanning the room's whole history; the outer query then flips those
// 50 rows back into chronological order.
func (q *Queries) ListRecentMessages(ctx context.Context, roomID int64) ([]ListRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentMessagesRow{}
	for rows.Next() {
		var i ListRecentMessagesRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Username,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
