// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Message struct {
	ID        int64              `json:"id"`
	RoomID    int64              `json:"room_id"`
	UserID    int64              `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MessageEmbedding struct {
	ID        int64              `json:"id"`
	RoomID    int64              `json:"room_id"`
	UserID    int64              `json:"user_id"`
	Body      string             `json:"body"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	Embedding pgvector.Vector    `json:"embedding"`
}

type Room struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RoomMember struct {
	RoomID   int64              `json:"room_id"`
	UserID   int64              `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type RoomRead struct {
	RoomID     int64              `json:"room_id"`
	UserID     int64              `json:"user_id"`
	LastReadAt pgtype.Timestamptz `json:"last_read_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
