// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error
	// How much of the log the indexer has covered — used by the /search handler to
	// give an honest "index is still warming up" answer instead of empty results.
	CountMessageEmbeddings(ctx context.Context, roomID int64) (int64, error)
	// Total unread, so the UI can say "summarising the latest 200 of 4,312" honestly
	// rather than silently truncating. Must apply the SAME three conditions as
	// ListUnreadMessages — if the count and the list disagree about what "unread"
	// means, the "(N unread — summarising the most recent M)" notice lies.
	CountUnreadMessages(ctx context.Context, arg CountUnreadMessagesParams) (int64, error)
	// created_at is passed in (not left to DEFAULT now()) so the stored time is when
	// the user actually sent the message, not when the persister happened to insert it.
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Read-state queries (Phase 5.4) — how far a user has read in a room, and what
	// they missed. Used only by "/catchup".
	GetRoomRead(ctx context.Context, arg GetRoomReadParams) (pgtype.Timestamptz, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error)
	// The last 50 messages of a room, oldest-first (chat reading order).
	// The inner query walks idx_messages_room_id_id backwards to grab the NEWEST 50
	// without scanning the room's whole history; the outer query then flips those
	// 50 rows back into chronological order.
	ListRecentMessages(ctx context.Context, roomID int64) ([]ListRecentMessagesRow, error)
	ListRooms(ctx context.Context) ([]Room, error)
	// Every room, plus whether THIS user is already a member of it.
	//
	// One query rather than "list the rooms" followed by a membership check per
	// room: that version costs one database round trip per room, so the list gets
	// slower the more rooms exist.
	//
	// LEFT JOIN, not JOIN. A LEFT JOIN keeps rooms that have no matching membership
	// row, filling the joined columns with NULL — which is exactly how a room you
	// are NOT in still appears in the list as something you could join. A plain JOIN
	// would silently drop every room you haven't joined, which is most of them.
	// The ::boolean cast is not decoration. sqlc infers Go types from what Postgres
	// reports, and it cannot work out the type of a bare IS NOT NULL expression, so
	// it falls back to interface{} and the Go code then won't compile. The cast
	// tells it. Same trick as ::vector in search.sql.
	ListRoomsForUser(ctx context.Context, userID int64) ([]ListRoomsForUserRow, error)
	// The messages a user missed, oldest-first, capped.
	//
	// "Missed" is three conditions, not two. The timestamp alone says "arrived after
	// you left", which is also true of messages YOU sent on returning — they land on
	// the far side of your own watermark. You have read what you wrote, so $3
	// excludes the asker. Without it /catchup answers "what happened here?" when the
	// question is "what did I miss?".
	//
	// Note we do NOT advance the watermark when a user sends. Talking is not reading:
	// you can reconnect, fire off a message without scrolling up, and still be owed a
	// summary of everything above it.
	//
	// The cap is not cosmetic. Prompt tokens are the expensive half of generation on
	// the homelab box (~71 tok/s prefill vs ~4.7 tok/s decode), and the model's
	// context is 2048 tokens. Someone away for a month must not push 5,000 messages
	// into it. We take the NEWEST 200 unread and flip them back to chronological —
	// the same inner/outer trick ListRecentMessages uses.
	ListUnreadMessages(ctx context.Context, arg ListUnreadMessagesParams) ([]ListUnreadMessagesRow, error)
	// Names for a set of user ids. Presence stores ids in Redis; the UI shows names.
	//
	// ANY() takes the whole set in ONE query. The obvious alternative — a lookup per
	// user — would mean one database round trip per person in the room, so a busy
	// room would cost more trips the more popular it got.
	//
	// ORDER BY username so the online list doesn't shuffle between refreshes, which
	// would look like people joining and leaving when nothing changed.
	ListUsernamesByIDs(ctx context.Context, dollar_1 []int64) ([]string, error)
	// Semantic search within one room, nearest-meaning first.
	//   <=>  is pgvector's cosine-DISTANCE operator: 0 = identical meaning, 2 = opposite.
	//   Ordering ASC by distance therefore puts the best matches first, and this is
	//   the operator the HNSW index was built for, so it doesn't scan the table.
	//   We return (1 - distance) as `similarity` because a number where HIGHER means
	//   BETTER is far easier to reason about in the UI.
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error)
	// The `::vector` cast is how sqlc learns the parameter's type: without it sqlc
	// has no idea what a vector is, with it the generated Go param is a
	// pgvector.Vector. Same trick news-feed uses.
	//
	// ON CONFLICT DO NOTHING makes the indexer IDEMPOTENT: Kafka can redeliver a
	// message, and re-indexing it must not create a second search hit.
	UpsertMessageEmbedding(ctx context.Context, arg UpsertMessageEmbeddingParams) error
	// Move a user's read watermark forward.
	//
	// GREATEST() is the important part: a watermark must only ever move FORWARD.
	// Without it, two tabs open on the same room would fight — the one that
	// disconnects second could be *behind*, and would drag the watermark backwards,
	// silently resurrecting messages the user already saw. Same lesson as the Kafka
	// offset: a watermark records how far you got, so it can only go up.
	UpsertRoomRead(ctx context.Context, arg UpsertRoomReadParams) error
}

var _ Querier = (*Queries)(nil)
