// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error
	// How much of the log the indexer has covered — used by the /search handler to
	// give an honest "index is still warming up" answer instead of empty results.
	CountMessageEmbeddings(ctx context.Context, roomID int64) (int64, error)
	// Total unread, so the UI can say "summarising the latest 200 of 4,312" honestly
	// rather than silently truncating.
	CountUnreadMessages(ctx context.Context, arg CountUnreadMessagesParams) (int64, error)
	// created_at is passed in (not left to DEFAULT now()) so the stored time is when
	// the user actually sent the message, not when the persister happened to insert it.
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Read-state queries (Phase 5.4) — how far a user has read in a room, and what
	// they missed. Used only by "/catchup".
	GetRoomRead(ctx context.Context, arg GetRoomReadParams) (pgtype.Timestamptz, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error)
	// The last 50 messages of a room, oldest-first (chat reading order).
	// The inner query walks idx_messages_room_id_id backwards to grab the NEWEST 50
	// without scanning the room's whole history; the outer query then flips those
	// 50 rows back into chronological order.
	ListRecentMessages(ctx context.Context, roomID int64) ([]ListRecentMessagesRow, error)
	ListRooms(ctx context.Context) ([]Room, error)
	// The messages a user missed, oldest-first, capped.
	//
	// The cap is not cosmetic. Prompt tokens are the expensive half of generation on
	// the homelab box (~71 tok/s prefill vs ~4.7 tok/s decode), and the model's
	// context is 2048 tokens. Someone away for a month must not push 5,000 messages
	// into it. We take the NEWEST 200 unread and flip them back to chronological —
	// the same inner/outer trick ListRecentMessages uses.
	ListUnreadMessages(ctx context.Context, arg ListUnreadMessagesParams) ([]ListUnreadMessagesRow, error)
	// Semantic search within one room, nearest-meaning first.
	//   <=>  is pgvector's cosine-DISTANCE operator: 0 = identical meaning, 2 = opposite.
	//   Ordering ASC by distance therefore puts the best matches first, and this is
	//   the operator the HNSW index was built for, so it doesn't scan the table.
	//   We return (1 - distance) as `similarity` because a number where HIGHER means
	//   BETTER is far easier to reason about in the UI.
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error)
	// The `::vector` cast is how sqlc learns the parameter's type: without it sqlc
	// has no idea what a vector is, with it the generated Go param is a
	// pgvector.Vector. Same trick news-feed uses.
	//
	// ON CONFLICT DO NOTHING makes the indexer IDEMPOTENT: Kafka can redeliver a
	// message, and re-indexing it must not create a second search hit.
	UpsertMessageEmbedding(ctx context.Context, arg UpsertMessageEmbeddingParams) error
	// Move a user's read watermark forward.
	//
	// GREATEST() is the important part: a watermark must only ever move FORWARD.
	// Without it, two tabs open on the same room would fight — the one that
	// disconnects second could be *behind*, and would drag the watermark backwards,
	// silently resurrecting messages the user already saw. Same lesson as the Kafka
	// offset: a watermark records how far you got, so it can only go up.
	UpsertRoomRead(ctx context.Context, arg UpsertRoomReadParams) error
}

var _ Querier = (*Queries)(nil)
