// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT (room_id, user_id) DO NOTHING
`

type AddRoomMemberParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember, arg.RoomID, arg.UserID)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, created_by)
VALUES ($1, $2)
RETURNING id, name, created_by, created_at
`

type CreateRoomParams struct {
	Name      string `json:"name"`
	CreatedBy int64  `json:"created_by"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.CreatedBy)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isRoomMember = `-- name: IsRoomMember :one
SELECT EXISTS (
    SELECT 1 FROM room_members
    WHERE room_id = $1 AND user_id = $2
) AS is_member
`

type IsRoomMemberParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRoomMember, arg.RoomID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, created_by, created_at FROM rooms
ORDER BY id
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsForUser = `-- name: ListRoomsForUser :many
SELECT r.id, r.name, (rm.user_id IS NOT NULL)::boolean AS is_member
FROM rooms r
LEFT JOIN room_members rm ON rm.room_id = r.id AND rm.user_id = $1
ORDER BY r.name
`

type ListRoomsForUserRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	IsMember bool   `json:"is_member"`
}

// Every room, plus whether THIS user is already a member of it.
//
// One query rather than "list the rooms" followed by a membership check per
// room: that version costs one database round trip per room, so the list gets
// slower the more rooms exist.
//
// LEFT JOIN, not JOIN. A LEFT JOIN keeps rooms that have no matching membership
// row, filling the joined columns with NULL — which is exactly how a room you
// are NOT in still appears in the list as something you could join. A plain JOIN
// would silently drop every room you haven't joined, which is most of them.
// The ::boolean cast is not decoration. sqlc infers Go types from what Postgres
// reports, and it cannot work out the type of a bare IS NOT NULL expression, so
// it falls back to interface{} and the Go code then won't compile. The cast
// tells it. Same trick as ::vector in search.sql.
func (q *Queries) ListRoomsForUser(ctx context.Context, userID int64) ([]ListRoomsForUserRow, error) {
	rows, err := q.db.Query(ctx, listRoomsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsForUserRow{}
	for rows.Next() {
		var i ListRoomsForUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsMember); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
