// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const countMessageEmbeddings = `-- name: CountMessageEmbeddings :one
SELECT count(*) FROM message_embeddings WHERE room_id = $1
`

// How much of the log the indexer has covered — used by the /search handler to
// give an honest "index is still warming up" answer instead of empty results.
func (q *Queries) CountMessageEmbeddings(ctx context.Context, roomID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMessageEmbeddings, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchMessages = `-- name: SearchMessages :many
SELECT
    me.room_id,
    me.user_id,
    u.username,
    me.body,
    me.sent_at,
    (1 - (me.embedding <=> $1::vector))::float8 AS similarity
FROM message_embeddings me
JOIN users u ON u.id = me.user_id
WHERE me.room_id = $2
ORDER BY me.embedding <=> $1::vector
LIMIT 10
`

type SearchMessagesParams struct {
	QueryEmbedding pgvector.Vector `json:"query_embedding"`
	RoomID         int64           `json:"room_id"`
}

type SearchMessagesRow struct {
	RoomID     int64              `json:"room_id"`
	UserID     int64              `json:"user_id"`
	Username   string             `json:"username"`
	Body       string             `json:"body"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
	Similarity float64            `json:"similarity"`
}

// Semantic search within one room, nearest-meaning first.
//
//	<=>  is pgvector's cosine-DISTANCE operator: 0 = identical meaning, 2 = opposite.
//	Ordering ASC by distance therefore puts the best matches first, and this is
//	the operator the HNSW index was built for, so it doesn't scan the table.
//	We return (1 - distance) as `similarity` because a number where HIGHER means
//	BETTER is far easier to reason about in the UI.
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages, arg.QueryEmbedding, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Username,
			&i.Body,
			&i.SentAt,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMessageEmbedding = `-- name: UpsertMessageEmbedding :exec
INSERT INTO message_embeddings (room_id, user_id, body, sent_at, embedding)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::vector
)
ON CONFLICT (room_id, user_id, sent_at) DO NOTHING
`

type UpsertMessageEmbeddingParams struct {
	RoomID    int64              `json:"room_id"`
	UserID    int64              `json:"user_id"`
	Body      string             `json:"body"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	Embedding pgvector.Vector    `json:"embedding"`
}

// The `::vector` cast is how sqlc learns the parameter's type: without it sqlc
// has no idea what a vector is, with it the generated Go param is a
// pgvector.Vector. Same trick news-feed uses.
//
// ON CONFLICT DO NOTHING makes the indexer IDEMPOTENT: Kafka can redeliver a
// message, and re-indexing it must not create a second search hit.
func (q *Queries) UpsertMessageEmbedding(ctx context.Context, arg UpsertMessageEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertMessageEmbedding,
		arg.RoomID,
		arg.UserID,
		arg.Body,
		arg.SentAt,
		arg.Embedding,
	)
	return err
}
