// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash)
VALUES ($1, $2)
RETURNING id, username, password_hash, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listUsernamesByIDs = `-- name: ListUsernamesByIDs :many
SELECT username FROM users
WHERE id = ANY($1::bigint[])
ORDER BY username
`

// Names for a set of user ids. Presence stores ids in Redis; the UI shows names.
//
// ANY() takes the whole set in ONE query. The obvious alternative — a lookup per
// user — would mean one database round trip per person in the room, so a busy
// room would cost more trips the more popular it got.
//
// ORDER BY username so the online list doesn't shuffle between refreshes, which
// would look like people joining and leaving when nothing changed.
func (q *Queries) ListUsernamesByIDs(ctx context.Context, dollar_1 []int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsernamesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
